name: Karatlove1
favicon: null
layout_spectrum: 0.75196
typography_spectrum: 0.52191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e3e3'
    - '#a2a2a0'
    - '#3f301c'
    - '#666545'
    - '#98794e'
  brandStrength: 0.5586144069675356
  lightness: 0.9735300503671169
  saturation: 0.8274698571767658
  rhythmicContrast: 0.5
purpose: []
